biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bibliotech.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bibliotech/urls.py
from django.urls import path

from . import views

app_name = 'livros'

urlpatterns = [
    path('', views.home, name="home"),
    path('livros/category/<int:category_id>/', views.category, name="category"),
    path('livros/<int:id>/', views.livro, name="livro"),
]

bibliotech/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Livro(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=250)
    slug = models.SlugField()
    cover = models.ImageField(upload_to='bibliotech/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

bibliotech/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.bibliotech.factory import make_book
from bibliotech.models import Livro

def home(request):
    livros = Livro.objects.all().order_by('-id')
    return render(request, 'bibliotech/pages/home.html', context= {
        'livros': livros,
    })

def category(request, category_id):
    livros = get_list_or_404 (
        Livro.objects.filter(
            category__id=category_id
        ).order_by('-id')
    )

    return render(request, 'bibliotech/pages/category.html', context= {
        'livros': livros,
        'title': f'{livros[0].category.name}'
    })

def livro(request, id):
    livro = get_object_or_404(Livro, pk=id)
    
    return render(request, 'bibliotech/pages/livro-view.html', context={
        'livro': livro,
        'is_detail_page': True,
    })

bibliotech/templates/bibliotech/pages/category.html
{% extends "global/base.html" %}

{% block title %} {{title}} | {% endblock title %}

{% block conteudo %}
    <div class="main-content main-content-list container">
        {% for livro in  livros %}
            {% include "bibliotech/partials/livro.html" %}
        {% endfor %}
    </div>
{% endblock conteudo %}

bibliotech/templates/bibliotech/pages/home.html
{% extends "global/base.html" %}

{% block conteudo %}
    <div class="container mb-5">
        <h1 class="title-container">Seus Livros</h1>
    </div>
    <div class="main-content main-content-list container">
        {% for livro in livros %}
            {% include "bibliotech/partials/livro.html" %}
            {% empty %}
                <h1>Você não possui Livros</h1>
        {% endfor %}
    </div>
{% endblock conteudo %}

bibliotech/templates/bibliotech/pages/livro-view.html
{% extends "global/base.html" %}
{% block title %} {{ livro.title }} |{% endblock title %}

{% block conteudo %}
        <div class="main-content main-content-detail container">
            {% include "bibliotech/partials/livro.html" %}
        </div>
{% endblock conteudo %}

bibliotech/templates/bibliotech/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css"
        integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/brands.min.css"
        integrity="sha512-DJLNx+VLY4aEiEQFjiawXaiceujj5GA7lIY8CHCIGQCBPfsEG0nGz1edb4Jvw1LR7q031zS5PpPqFuPA8ihlRA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/solid.min.css"
        integrity="sha512-Hp+WwK4QdKZk9/W0ViDvLunYjFrGJmNDt6sCflZNkjgvNq9mY+0tMbd6tWMiAlcf1OQyqL4gn2rYp7UsfssZPA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{% static "bibliotech/css/style-home.css" %}">
    <link rel="stylesheet" href="{% static "global/css/global-style-home.css" %}">

bibliotech/templates/bibliotech/partials/header.html
{% load static %}

<header>
    <nav class="navbar navegacao-topo fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <h1 class="title-container">Home</h1>
            <div class="offcanvas barra-lateral offcanvas-start" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header header-top">
                    <img src="{% static "bibliotech/image/logo.png" %}" alt="Logo" width="250">
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a href="{% url 'livros:home' %}">
                                <i class="fa-solid fa-house"></i>
                                <span>Home</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#">
                                <i class="fa-solid fa-calendar-days"></i>
                                <span>Emprestimos</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#">
                                <i class="fa-solid fa-file-invoice-dollar"></i>
                                <span>Multas</span>
                            </a>
                        </li>
                        <li class="nav-item btn-logout">
                            <a href="#">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                <span>Log Out</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

bibliotech/templates/bibliotech/partials/livro.html
<div class="livro livro-list-item">
    <div class="livro-image">
        <a href="{% url "livros:livro" livro.id %}">
            <img src="{{ livro.cover.url }}" alt="">
        </a>
    </div>
    <div class="livro-title-container">
        <h2 class="livro-title">{{ livro.title }}</h2>
    </div>

    <div class="livro-author">
        <span class="livro-author-item">
            <i class="fas fa-user">
                {% if livro.author.first_name %}
                    {{ livro.author.first_name }} {{ livro.author.last_name }}
                {% else %}
                    {{ livro.author.username }}
                {% endif %}
            </i>
        </span>
        <span class="livro-author-item">
            <a href="{% url "livros:category" livro.category.id %}">
                <i class="fas fa-layer-group">
                    <span>{{ livro.category.name }}</span>
                </i>
            </a>
        </span>
    </div>

    {% if is_detail_page is True %}
        <div class="livro-descricao">
            {{ livro.description }}
        </div>
    {% endif %}
    
    {% if is_detail_page is True %}
    <div class=" d-grid gap-2 btn-actions">
        <button type="button" class="btn btn-success btn-lg mb-3">Renovar</button>
        <button type="button" class="btn btn-warning btn-lg">Devolver</button>
    </div>
    {% endif %}
</div>

bibliotech/templates/bibliotech/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>